name: otp_sms_retriever
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  permission_handler: ^11.3.1
  pinput: ^5.0.1
  shared_preferences: ^2.4.0
  sms_autofill: ^2.4.1
  # sms_otp_auto_verify: 
  # android_sms_retriever: ^1.3.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/otp_code.png"  # Your app icon
  adaptive_icon_background: "#ffffff"  # Optional for Android adaptive icon

flutter:
  uses-material-design: true

  assets:
    - assets/otp_code.png


